version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_URL: "/docker/registry/url"
    DOCKER_USERNAME: "/docker/registry/username"
    DOCKER_PASSWORD: "/docker/registry/password"

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Listing project files..."
      - ls -R
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Logging into Docker registry..."
      - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t "$DOCKER_REGISTRY_URL/simple-python-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/simple-python-app:latest"

  post_build:
    commands:
      - echo "Build is Successful"
